name = "CoreNLPClient"
uuid = "128a14f7-a34c-4ab5-b797-7dc430f1f974"
authors = ["Junfeng Wu <wujunfeng1@gmail.com>"]
version = "0.1.6"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
julia = "1"
HTTP = "0.9.3"
